---
- name: Create systemd unit file for containerd
  template:
    dest: /etc/systemd/system/containerd.service
    src: etc/systemd/system/containerd-flatcar.service
    mode: 0600

- name: Create containerd memory pressure drop in file
  template:
    dest: /etc/systemd/system/containerd.service.d/memory-pressure.conf
    src: etc/systemd/system/containerd.service.d/memory-pressure.conf
    mode: 0644

- name: Create containerd max tasks drop in file
  template:
    dest: /etc/systemd/system/containerd.service.d/max-tasks.conf
    src: etc/systemd/system/containerd.service.d/max-tasks.conf
    mode: 0644

- name: Create containerd http proxy conf file if needed
  template:
    dest: /etc/systemd/system/containerd.service.d/http-proxy.conf
    src: etc/systemd/system/containerd.service.d/http-proxy.conf
    mode: 0644
  when: http_proxy is defined or https_proxy is defined

- name: add to PATH unpack docker to path
  copy:
    content: "export PATH=$PATH:/run/torcx/unpack/docker/bin/"
    dest: "/etc/profile.d/my_path.sh"

- name: ensure cgroups v2 are disabled
  command: grep -q systemd.unified_cgroup_hierarchy=0 /usr/share/oem/grub.cfg
  changed_when: no
  failed_when: false
  register: cgroupsv2_check

- name: cgroups setup
  when:
    - cgroupsv2_check.rc != 0
  block:
    - name: disable cgroups v2
      command: sed -E -i 's/^(set linux_append=.*)"$/\1 systemd.unified_cgroup_hierarchy=0 systemd.legacy_systemd_cgroup_controller"/g' /usr/share/oem/grub.cfg
