---
# NOTE This is distinct from the containerd.io package
- name: remove preinstalled containerd
  zypper:
    name: containerd
    state: absent

- name: remove versionlock for containerd
  command: zypper removelock containerd.io
  args:
    warn: false
  ignore_errors: true
  register: command_result
  changed_when: |
    'command_result.stdout is regex(".*lock has been successfully removed.")'
  when:
    - exportedversionlocklist is defined and exportedversionlocklist.stdout is defined
    - "(
      'containerd.io' in exportedversionlocklist.stdout and
      not 'Keep installed : containerd.io-' + containerd_version in exportedversionlocklist.stdout
      )"

# remove previous install with KIB through an OS package
- name: remove containerd.io package
  zypper:
    name: "containerd.io"
    state: absent
  register: result
  until: result is success
  retries: 15
  delay: 60

- name: install libseccomp package
  zypper:
    name: libseccomp2
    state: present
  register: result
  until: result is success
  retries: 3
  delay: 3
