---
run:
  timeout: 3m

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

linters-settings:
  depguard:
    list-type: blacklist
    packages:
      - k8s.io/kubernetes
    packages-with-error-message:
      - k8s.io/kubernetes: >-
          Avoid k8s.io/kubernetes if possible to reduce transitive dependencies
  dupl:
    threshold: 100
  exhaustive:
    default-signifies-exhaustive: true
  funlen:
    lines: 100
    statements: 50
  gci:
    local-prefixes: github.com/mesosphere/konvoy-image-builder
  goconst:
    min-len: 2
    min-occurrences: 2
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
  gocyclo:
    min-complexity: 15
  goimports:
    local-prefixes: github.com/mesosphere/konvoy-image-builder
  gomnd:
    settings:
      mnd:
        # don't include "argument", "operation", and "assign"
        checks:
          - case
          - condition
          - return
  govet:
    check-shadowing: true
    enable-all: true
    disable:
      - fieldalignment
  lll:
    line-length: 140
  misspell:
    locale: US
  nolintlint:
    allow-leading-space: false
    allow-unused: false
    require-explanation: true
    require-specific: true
  revive:
    confidence: 0.0
    errorCode: 1

linters:
  # please, do not use `enable-all`: it's deprecated and will be removed soon.
  # inverted configuration with `enable-all` and `disable` is not scalable
  # during updates of golangci-lint
  disable-all: true
  enable:
    - asciicheck
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - dupl
    - errcheck
    - exhaustive
    - exportloopref
    - funlen
    - gci
    - goconst
    - gocyclo
    - godot
    - gofmt
    - gofumpt
    - goimports
    - gomnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - makezero
    - misspell
    - nakedret
    - nestif
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - staticcheck
    - structcheck
    - stylecheck
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace
    # NOTE(jkoelker) disable wrapcheck until >1.10 is in golangci-lint
    #    - wrapcheck
