---
run:
  timeout: 3m

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

linters-settings:
  depguard:
    rules:
      main:
        deny:
          - pkg: "k8s.io/kubernetes"
            desc: "Avoid if possible to reduce transitive dependencies"
  dupl:
    threshold: 100
  exhaustive:
    default-signifies-exhaustive: true
  funlen:
    lines: 100
    statements: 50
  gci:
    sections:
      - standard # Standard section: captures all standard packages.
      - default # Default section: contains all imports that could not be matched to another section type.
      - prefix(github.com/mesosphere/konvoy-image-builder) # Custom section: groups all imports with the specified Prefix.
      - blank # Blank section: contains all blank imports. This section is not present unless explicitly enabled.
      - dot # Dot section: contains all dot imports. This section is not present unless explicitly enabled.
      - alias # Alias section: contains all alias imports. This section is not present unless explicitly enabled.
      - localmodule # Local module section: contains all local packages. This section is not present unless explicitly enabled.
  goconst:
    min-len: 2
    min-occurrences: 2
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
  gocyclo:
    min-complexity: 15
  mnd:
    checks:
    - case
    - condition
    - return
  govet:
    enable-all: true
    disable:
      - fieldalignment
  lll:
    line-length: 140
  misspell:
    locale: US
  nolintlint:
    allow-leading-space: false
    allow-unused: false
    require-explanation: true
    require-specific: true
  revive:
    confidence: 0.0
    errorCode: 1

linters:
  # please, do not use `enable-all`: it's deprecated and will be removed soon.
  # inverted configuration with `enable-all` and `disable` is not scalable
  # during updates of golangci-lint
  disable-all: true
  enable:
    - asciicheck
    - bodyclose
    - depguard
    - dogsled
    - dupl
    - errcheck
    - exhaustive
    - exportloopref
    - funlen
    - gci
    - goconst
    - gocyclo
    - godot
    - gofmt
    - gofumpt
    - goimports
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - makezero
    - misspell
    - mnd
    - nakedret
    - nestif
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - staticcheck
    - stylecheck
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
    # NOTE(jkoelker) disable wrapcheck until >1.10 is in golangci-lint
    #    - wrapcheck
