---
before:
  hooks:
    - go mod download
    - go mod tidy

# NOTE(jkoelker) the changelog is managed by `release-please`
changelog:
  skip: true

builds:
  - main: ./cmd/konvoy-image/main.go
    id: konvoy-image
    binary: konvoy-image
    mod_timestamp: "{{ .CommitTimestamp }}"
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X {{ .ModulePath }}/pkg/version.version=v{{trimprefix .Version "v"}}
      - -X {{ .ModulePath }}/pkg/version.major={{ .Major }}
      - -X {{ .ModulePath }}/pkg/version.minor={{ .Minor }}
      - -X {{ .ModulePath }}/pkg/version.patch={{ .Patch }}
      - -X {{ .ModulePath }}/pkg/version.revision={{ .FullCommit }}
      - -X {{ .ModulePath }}/pkg/version.commitDate={{ .CommitDate }}
      - -X {{ .ModulePath }}/pkg/version.branch={{ .Branch }}
      - -X {{ .ModulePath }}/pkg/version.builtBy=goreleaser
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64

  - main: ./cmd/konvoy-image-wrapper/main.go
    id: konvoy-image-wrapper
    binary: konvoy-image
    mod_timestamp: "{{ .CommitTimestamp }}"
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    tags:
      - EMBED_DOCKER_IMAGE
    ldflags:
      - -s -w
      - -X {{ .ModulePath }}/pkg/version.version=v{{trimprefix .Version "v"}}
      - -X {{ .ModulePath }}/pkg/version.major={{ .Major }}
      - -X {{ .ModulePath }}/pkg/version.minor={{ .Minor }}
      - -X {{ .ModulePath }}/pkg/version.patch={{ .Patch }}
      - -X {{ .ModulePath }}/pkg/version.revision={{ .FullCommit }}
      - -X {{ .ModulePath }}/pkg/version.commitDate={{ .CommitDate }}
      - -X {{ .ModulePath }}/pkg/version.branch={{ .Branch }}
      - -X {{ .ModulePath }}/pkg/version.builtBy=goreleaser
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
    hooks:
      pre:
        - make cmd/konvoy-image-wrapper/image/konvoy-image-builder.tar.gz

dockers:
  - dockerfile: Dockerfile
    use: buildx
    image_templates:
      - 'mesosphere/konvoy-image-builder:v{{ trimprefix .Version "v" }}-amd64'
    ids:
      - konvoy-image
    # NOTE(jkoelker) Exclude `--pull` from the build flags, since the devkit
    #                was just build and is local, it will not be found.
    build_flag_templates:
      - '--build-arg=BASE=mesosphere/konvoy-image-builder:latest-devkit'
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.name={{ .ProjectName }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - '--label=org.opencontainers.image.version=v{{trimprefix .Version "v"}}'
      - "--label=org.opencontainers.image.source={{ .GitURL }}"
      - "--platform=linux/amd64"
    skip_push: false
    extra_files:
      - bin
      - images
      - ansible
      - packer
      - requirements.txt

  - dockerfile: Dockerfile
    use: buildx
    image_templates:
      - 'mesosphere/konvoy-image-builder:v{{ trimprefix .Version "v" }}-arm64'
    ids:
      - konvoy-image
    # NOTE(jkoelker) Exclude `--pull` from the build flags, since the devkit
    #                was just build and is local, it will not be found.
    build_flag_templates:
      - '--build-arg=BASE=mesosphere/konvoy-image-builder:latest-devkit-arm64'
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.name={{ .ProjectName }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - '--label=org.opencontainers.image.version=v{{trimprefix .Version "v"}}'
      - "--label=org.opencontainers.image.source={{ .GitURL }}"
      - "--platform=linux/arm64"
    skip_push: false
    extra_files:
      - bin
      - images
      - ansible
      - packer

archives:
  - id: konvoy-image-bundle
    builds:
      - konvoy-image-wrapper
    name_template: "konvoy-image-bundle-v{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - ansible
      - goss
      - images
      - overrides
      - packer
      - LICENSE
      - README.md

checksum:
  # override the name template to include the "v" prefix
  name_template: '{{ .ProjectName }}_v{{trimprefix .Version "v"}}_checksums.txt'

release:
  github:
  prerelease: auto
  ids:
    - konvoy-image-bundle
