---
# If image is present, its name is written to stdout. Return code is 0.
#   > ctr --namespace k8s.io images check -q name==docker.io/mesosphere/pause-alpine:3.2; echo $?
#   docker.io/mesosphere/pause-alpine:3.2
#   0
#
# If image is not present, or is present, but some layer is missing, its name is not written to stdout. Return code is 0.
#   > ctr --namespace k8s.io images check -q name==docker.io/mesosphere/pause-alpine:999; echo $?
#   0
#
# NOTE ctr must be in the PATH of the ansible process.
- name: check existing image to ensure all content is available locally  # noqa no-changed-when
  command: ctr --address {{ containerd_cri_socket }} --namespace k8s.io images check name=={{ image_name }}
  register: ctr_images_check
  failed_when: ctr_images_check.rc != 0
  changed_when: false

- name: pull image  # noqa no-changed-when
  command: crictl pull {{ image_name }}
  when: image_name not in ctr_images_check.stdout
  register: ctr_images_pull
  failed_when: ctr_images_pull.rc != 0
  changed_when: true
