- name: list files in the local image cache
  find:
    paths:
    - "{{ images_cache }}"
    use_regex: true
    patterns:
    - .*\.tar(\.gz)?
    file_type: file
  register: images_cache_find_result
  changed_when: false

- block:
    - name: import images from files in the local images cache # noqa no-changed-when
      shell:
        executable: /bin/bash
        cmd: |
          {{ mindthegap_binary_location_on_remote }} import image-bundle --image-bundle={{ item }};
          if [[ $? -ne 0 ]]; then
            ctr --address {{ containerd_cri_socket }} --namespace k8s.io images import <(gzip --decompress --stdout {{ item }});
          fi
      with_items: "{{  images_cache_find_result.files | map(attribute='path') | list }}"

    - name: remove mindthegap if present
      file:
        path: "{{ mindthegap_binary_location_on_remote }}"
        state: absent
  when: images_cache_find_result.files | length > 0
