# Copyright 2019 The Kubernetes Authors.

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

# http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
- name: (Debian) Install gcloud CLI
  when: ansible_os_family == "Debian"
  block:
    - name: (Debian) Add gcloud repository key
      ansible.builtin.get_url:
        url: "https://packages.cloud.google.com/apt/doc/apt-key.gpg"
        dest: /usr/share/keyrings/google-cloud-apt-repo.asc
        mode: '0644'
        force: true
      retries: 3
      delay: 3
    - name: (Debian) Add gcloud repository
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/google-cloud-apt-repo.asc] http://packages.cloud.google.com/apt cloud-sdk main"
        state: present
        update_cache: true
      retries: 3
      delay: 3
    - name: (Debian) Install gcloud CLI package
      ansible.builtin.apt:
        name: google-cloud-cli
        state: present
      retries: 3
      delay: 3

- name: (RedHat) Install gcloud CLI
  when: ansible_os_family == "RedHat"
  block:
    - name: (RedHat) Add gcloud repository
      ansible.builtin.yum_repository:
        name: Google Cloud SDK
        description: Google Cloud SDK
        enabled: true
        baseurl: https://packages.cloud.google.com/yum/repos/cloud-sdk-el9-x86_64
        gpgcheck: true
        repo_gpgcheck: false
        gpgkey: https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
      retries: 3
      delay: 3
    - name: (RedHat) Install gcloud CLI package
      ansible.builtin.yum:
        name: google-cloud-cli
        state: present
      retries: 3
      delay: 3

- name: (SUSE) Install gcloud CLI
  when: ansible_os_family == "Suse"
  block:
    - name: (SUSE) Add gcloud repository
      community.general.zypper_repository:
        name: Google Cloud SDK
        repo: https://packages.cloud.google.com/yum/repos/cloud-sdk-el9-x86_64
        auto_import_keys: true
      retries: 3
      delay: 3
    - name: (SUSE) Install gcloud CLI package
      community.general.zypper:
        name: google-cloud-cli
        state: present
      retries: 3
      delay: 3

- name: Install cloud-init packages
  block:
    - name: (SUSE) Install cloud-init packages
      community.general.zypper:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - cloud-init
          - cloud-init-guestinfo
      when: ansible_os_family == "Suse"
      register: result
      until: result is success
      retries: 15
      delay: 60
    - name: (RedHat) Install cloud-init packages
      ansible.builtin.yum:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - cloud-init
          - cloud-utils-growpart
          - python2-pip
      when: ansible_os_family == "RedHat"
    - name: (Debian) Install cloud-init packages
      ansible.builtin.apt:
        name: "{{ packages }}"
        state: present
        force_apt_get: true
      vars:
        packages:
          - cloud-init
          - cloud-guest-utils
          - cloud-initramfs-copymods
          - cloud-initramfs-dyn-netconf
      when: ansible_os_family == "Debian"
