- name: Install cloud-init packages
  apt:
    name: "{{ packages }}"
    state: present
    force_apt_get: true
  vars:
    packages:
      - cloud-init
      - cloud-guest-utils
      - cloud-initramfs-copymods
      - cloud-initramfs-dyn-netconf
  when: ansible_os_family == "Debian"

- name: Install cloud-init packages
  yum:
    name: "{{ packages }}"
    state: present
    enablerepo: "{{ 'offline' if offline_mode_enabled else '' }}"
    disablerepo: "{{ '*' if offline_mode_enabled else '' }}"
  vars:
    packages:
      - cloud-init
      - cloud-utils-growpart
      - "python{{ '3' if ansible_distribution_major_version|int >= 9 else '2'}}-pip"
  when: ansible_os_family == "RedHat"

- name: Install cloud-init packages
  zypper:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - cloud-init
      - cloud-init-vmware-guestinfo
  when: ansible_os_family == "Suse"
  register: result
  until: result is success
  retries: 15
  delay: 60

- name: Install cloud-init and tools for VMware Photon OS
  command: tdnf install {{ packages }} -y
  vars:
    packages: "cloud-init cloud-utils python3-netifaces"
  when: ansible_os_family == "VMware Photon OS"

# pip on CentOS needs to be upgraded, but since it's still
# Python 2.7, need < 21.0
- name: Upgrade pip
  pip:
    name: pip<21.0
    extra_args: "{{ '--no-index --find-links=' + pip_packages_remote_filesystem_repo_path if offline_mode_enabled }}"
    state: forcereinstall
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == '7'

- name: Copy vmware guestinfo datasource
  copy:
    src: "{{ item }}"
    dest: /tmp/
    owner: root
    group: root
    mode: 0755
  with_items:
    - cloud-init-vmware.sh
    - DataSourceVMwareGuestInfo.py

- name: Copy cloud-init config file for vmware
  copy:
    src: files/etc/cloud/cloud.cfg.d/99-DataSourceVMwareGuestInfo.cfg
    dest: /etc/cloud/cloud.cfg.d/99-DataSourceVMwareGuestInfo.cfg
    owner: root
    group: root
    mode: 0644

- name: Remove subiquity-disable-cloudinit-networking.cfg
  file:
    path: /etc/cloud/cloud.cfg.d/subiquity-disable-cloudinit-networking.cfg
    state: absent

- name: Remove 99-installer.cfg
  file:
    path: /etc/cloud/cloud.cfg.d/99-installer.cfg
    state: absent

# this program used by ds-identify to determine whether or not the
# VMwareGuestInfo datasource is useable.
- name: Create ds-check program to verify VMwareGuestInfo datasource
  copy:
    src: files/dscheck_VMwareGuestInfo.sh
    dest: /usr/bin/dscheck_VMwareGuestInfo
    owner: root
    group: root
    mode: 0755

- name: Execute cloud-init-vmware.sh
  shell: bash -o errexit -o pipefail /tmp/cloud-init-vmware.sh
  environment:
    VMWARE_DS_PATH: '/tmp/DataSourceVMwareGuestInfo.py'

- name: Remove cloud-init-vmware.sh
  file:
    path: /tmp/cloud-init-vmware.sh
    state: absent

- name: >-
    Remove cloud-init /etc/cloud/cloud.cfg.d/99-disable-networking-config.cfg
  file:
    path: /etc/cloud/cloud.cfg.d/99-disable-networking-config.cfg
    state: absent
  when: ansible_os_family == "VMware Photon OS"
