---

- name: install kernel {{ hostvars[inventory_hostname].ansible_kernel }} headers and devel
  dnf:
    name:
      - "kernel-headers-{{ hostvars[inventory_hostname].ansible_kernel }}"
      - "kernel-devel-{{ hostvars[inventory_hostname].ansible_kernel }}"
    state: present

- name: install additional Nvidia runfile prerequisites
  dnf:
    name:
      - elfutils-libelf-devel
      - gcc
      - make
    state: present
