---
- name: install epel-release
  yum:
    name: epel-release
    state: present
    update_cache: true
  register: result
  until: result is success
  retries: 5
  delay: 3
  when:
    - not offline_mode_enabled

- name: find this kernel headers
  yum:
    list: "kernel-headers-{{ hostvars[inventory_hostname].ansible_kernel }}"
  register: pkgheaders
  when:
    - not offline_mode_enabled

- name: get CentOS specific release version
  slurp:
    src: /etc/centos-release
  register: os_release_file

# If possible we use headers from main OS repo for this kernel.
- name: install Kernel Header and Devel from OS repo for Current Kernel
  yum:
    name:
      - "kernel-headers-{{ hostvars[inventory_hostname].ansible_kernel }}"
      - "kernel-devel-{{ hostvars[inventory_hostname].ansible_kernel }}"
    state: present
    enablerepo: "{{ 'offline' if offline_mode_enabled else '' }}"
    disablerepo: "{{ '*' if offline_mode_enabled else '' }}"
    update_cache: true
  when:
    - offline_mode_enabled or pkgheaders.results|length > 0

- name: install runfile prereqs
  yum:
    name:
      - make
      - gcc
    state: present
    enablerepo: "{{ 'offline' if offline_mode_enabled else '' }}"
    disablerepo: "{{ '*' if offline_mode_enabled else '' }}"
  register: result
  until: result is success
  retries: 5
  delay: 3
