---
- name: add epel gpg key
  rpm_key:
    state: present
    key: "{{ epel_centos_8_rpm_gpg_key }}"

- name: install epel-release
  dnf:
    name: "{{ epel_centos_8_rpm }}"
    state: present

- name: install kernel {{ hostvars[inventory_hostname].ansible_kernel }} headers and devel
  dnf:
    name:
      - "kernel-headers-{{ hostvars[inventory_hostname].ansible_kernel }}"
      - "kernel-devel-{{ hostvars[inventory_hostname].ansible_kernel }}"
    state: present

- name: install additional Nvidia runfile prerequisites
  dnf:
    name:
      - elfutils-libelf-devel
      - gcc
      - make
    state: present

- name: add Nvidia repository for cuda drivers and tools
  yum_repository:
    name: cuda
    description: NVIDIA cuda repository
    enabled: true
    baseurl: "{{ nvidia_repo_baseurl }}"
    gpgkey: "{{ nvidia_repo_gpgkey }}"
    gpgcheck: true

- name: create temporary run file directory
  ansible.builtin.tempfile:
    state: directory
    suffix: build
  register: runfile_dir

# It appears impossible to pin a specific CUDA version on RHEL8 unless
# one uses the runfile installer.
# Installing `cuda-XX-X` will result in sliding CUDA versions.
# TODO(tillt): Find a way that spares us the runfile.
- name: download Nvidia driver installer
  get_url:
    url: "{{ nvidia_runfile_installer_url }}"
    dest: "{{ runfile_dir.path }}/{{ nvidia_runfile_installer }}"
    mode: 0755
  retries: 3
  delay: 3

- name: run Nvidia driver installer
  command: "{{ runfile_dir.path }}/{{ nvidia_runfile_installer }} --silent"

- name: add libnvidia-container repository
  yum_repository:
    name: libnvidia-container
    description: NVIDIA cuda repository
    enabled: false
    baseurl: "{{ libnvidia_container_repo_rhel }}"
    gpgkey: "{{ libnvidia_container_repo_gpgkey }}"
    gpgcheck: true

- name: install libnvidia-container
  dnf:
    name: libnvidia-container1
    enablerepo: libnvidia-container
    state: present

- name: add libnvidia-container-runtime repository
  yum_repository:
    name: nvidia-container-runtime
    description: NVIDIA cuda repository
    enabled: false
    baseurl: "{{ nvidia_container_runtime_repo_rhel }}"
    gpgkey: "{{ nvidia_container_runtime_repo_gpgkey }}"
    gpgcheck: true

- name: install nvidia-container-tools
  dnf:
    name: libnvidia-container-tools
    enablerepo:
      - libnvidia-container
    state: present

- name: install nvidia-container-runtime
  dnf:
    name: "{{ nvidia_container_runtime_package }}"
    enablerepo:
      - nvidia-container-runtime
    state: present
