---
- name: install epel-release
  yum:
    name: epel-release
    state: present
    update_cache: true
  register: result
  until: result is success
  retries: 5
  delay: 3

- name: find this kernel headers
  yum:
    list: "kernel-headers-{{ hostvars[inventory_hostname].ansible_kernel }}"
  register: pkgheaders

- name: get CentOS specific release version
  slurp:
    src: /etc/centos-release
  register: os_release_file

# If possible we use headers from main OS repo for this kernel.
- name: Install Kernel Header and Devel from OS repo for Current Kernel
  yum:
    name:
      - "kernel-headers-{{ hostvars[inventory_hostname].ansible_kernel }}"
      - "kernel-devel-{{ hostvars[inventory_hostname].ansible_kernel }}"
  when: pkgheaders.results|length > 0
# CentOS VAULT - Kernel Headers not available in main OS repo anymore. Use Vault for this release
- name: CentOS VAULT - Kernel Headers not available in main OS repo anymore. Use Vault for this release
  # 2019-09-18: CentOS created new version 7.7.1908 and rebased the /7 repo.
  # But vault for 7.6.1810 is not available but mirror is
  when: pkgheaders.results|length == 0
  block:
    - name: ThisVault
      yum_repository:
        name: ThisVault
        description: This Vault
        baseurl: "{{ vault_repo_baseurl }}"
        enabled: false
    - name: ThisVault - Install Kernel Headers for Current Kernel
      yum:
        enablerepo: ThisVault
        name: "kernel-headers-{{ hostvars[inventory_hostname].ansible_kernel | regex_search('\\d+\\.\\d+\\.\\d+-\\d+') }}.el{{ hostvars[inventory_hostname].ansible_distribution_major_version }}"
    - name: ThisVault - Install Kernel Devel for Current Kernel
      yum:
        enablerepo: ThisVault
        name: "kernel-devel-{{ hostvars[inventory_hostname].ansible_kernel | regex_search('\\d+\\.\\d+\\.\\d+-\\d+') }}.el{{ hostvars[inventory_hostname].ansible_distribution_major_version }}"
  rescue:
    - name: Centos mirror this version
      yum_repository:
        name: CentosThisVersionMirror
        description: Centos mirror this version
        baseurl: "{{ mirror_repo_baseurl }}"
        enabled: false
    - name: CentosThisVersionMirror - register mirror as the repository to be used
      set_fact:
        old_package_repo: CentosThisVersionMirror
    - name: CentosThisVersionMirror - Install Kernel Headers for Current Kernel
      yum:
        enablerepo: "{{ old_package_repo }}"
        name: "kernel-headers-{{ hostvars[inventory_hostname].ansible_kernel | regex_search('\\d+\\.\\d+\\.\\d+-\\d+') }}.el{{ hostvars[inventory_hostname].ansible_distribution_major_version }}"
    - name: CentosThisVersionMirror - Install Kernel Devel for Current Kernel
      yum:
        enablerepo: "{{ old_package_repo }}"
        name: "kernel-devel-{{ hostvars[inventory_hostname].ansible_kernel | regex_search('\\d+\\.\\d+\\.\\d+-\\d+') }}.el{{ hostvars[inventory_hostname].ansible_distribution_major_version }}"
  always:
    - name: Ensure to link against merged kernel headers
      file:
        dest: "/lib/modules/{{ hostvars[inventory_hostname].ansible_kernel }}/build"
        src: "/usr/src/kernels/{{ hostvars[inventory_hostname].ansible_kernel | regex_search('\\d+\\.\\d+\\.\\d+-\\d+') }}.el{{ hostvars[inventory_hostname].ansible_distribution_major_version }}.x86_64/"
        force: yes
        state: link
        follow: false

# ensure nouveau being unloaded
- name: Ensure nouveau being unloaded
  modprobe:
    name: nouveau
    state: absent
  changed_when: False

# Install NVIDIA repository, driver and tools
- name: Add NVIDIA repository for drivers and tools
  yum_repository:
    name: cuda
    description: NVIDIA driver repository
    enabled: true
    baseurl: "{{ nvidia_repo_baseurl }}"
    gpgkey: "{{ nvidia_repo_gpgkey }}"
    gpgcheck: true
- name: Install nvidia driver
  yum:
    name:
      - "{{ nvidia_driver_package }}"
    state: present
  register: result
  until: result is success
  retries: 5
  delay: 3

# libnvidia-container
- name: Add libnvidia-container repository
  yum_repository:
    name: libnvidia-container
    description: NVIDIA libnvidia-container repository
    enabled: false
    baseurl: "{{ libnvidia_container_repo_centos }}"
    gpgkey: "{{ libnvidia_container_repo_gpgkey }}"
    gpgcheck: true

- name: Install libnvidia-container
  yum:
    name: libnvidia-container1
    enablerepo: libnvidia-container
    state: present
  register: result
  until: result is success
  retries: 5
  delay: 3

- name: Add libnvidia-container-runtime repository
  yum_repository:
    name: nvidia-container-runtime
    description: NVIDIA libnvidia-container-runtime repository
    enabled: false
    baseurl: "{{ nvidia_container_runtime_repo_centos }}"
    gpgkey: "{{ nvidia_container_runtime_repo_gpgkey }}"
    gpgcheck: true

- name: Install nvidia-container-tools
  yum:
    name: libnvidia-container-tools
    enablerepo:
      - libnvidia-container
    state: present
  register: result
  until: result is success
  retries: 5
  delay: 3

- name: Install nvidia-container-runtime
  yum:
    name: "{{ nvidia_container_runtime_package }}"
    enablerepo:
      - nvidia-container-runtime
    state: present
  register: result
  until: result is success
  retries: 5
  delay: 3
