# from: https://github.com/kubernetes-sigs/image-builder/blob/892282320fb06d998ab4486d232940abe79a3468/images/capi/ansible/roles/kubernetes/tasks/crictl-url.yml
---
- name: download crictl
  changed_when: False
  get_url:
    url: "{{ crictl_url }}"
    checksum: "sha256:{{ crictl_sha256 }}"
    dest: /tmp/crictl.tar.gz
    mode: 0600

- name: Create "{{ sysusrlocal_prefix }}/bin" directory
  changed_when: False
  file:
    state: directory
    path: "{{ sysusrlocal_prefix if ansible_os_family != \"Flatcar\" else flatcar_sysusrlocal_prefix }}/bin"
    mode: 0755
    owner: root
    group: root

- name: unpack crictl
  changed_when: False
  unarchive:
    remote_src: True
    src: /tmp/crictl.tar.gz
    dest: "{{ sysusrlocal_prefix if ansible_os_family != \"Flatcar\" else flatcar_sysusrlocal_prefix }}/bin"
    extra_opts:
      - --no-overwrite-dir

- name: Remove crictl tarball
  changed_when: False
  file:
    state: absent
    path: /tmp/crictl.tar.gz
