---
- name: add epel gpg key
  rpm_key:
    state: present
    key: "{{ epel_centos_8_rpm_gpg_key }}"
  when:
    - ansible_distribution_major_version == '8'

- name: add epel gpg key
  rpm_key:
    state: present
    key: "{{ epel_centos_7_rpm_gpg_key }}"
  when:
    - ansible_distribution_major_version == '7'

- name: install epel-release
  yum:
    name: "{{ epel_centos_8_rpm }}"
    state: present
  when:
    - ansible_distribution_major_version == '8'

- name: install epel-release
  yum:
    name: "{{ epel_centos_7_rpm }}"
    state: present
  when:
    - ansible_distribution_major_version == '7'
