---
- name: install common packages
  zypper:
    name:
      - audit
      - ca-certificates
      - conntrack-tools
      - chrony
      - curl
      - ebtables
      - open-vm-tools
      - python3-pip
      - python3-netifaces
      - python3-requests
      - socat
      - sysstat
      - nfs-utils
    state: present
  register: result
  until: result is success
  retries: 15
  delay: 60

- name: check if versionlock exists
  command: zypper locks -s
  register: versionlocklist
  args:
    warn: false
  ignore_errors: True
  changed_when: false

- name: check if versionlock exists
  command: zypper locks -s
  register: versionlocklist
  args:
    warn: false
  ignore_errors: True
  changed_when: false

- name: remove preinstalled containerd
  zypper:
    name: containerd
    state: absent

- name: remove versionlock for containerd
  command: zypper removelock containerd.io
  args:
    warn: false
  ignore_errors: True
  register: command_result
  changed_when: 'command_result.stdout is regex(".*lock has been successfully removed.")'
  when:
    - versionlocklist is defined and versionlocklist.stdout is defined
    - "'containerd.io' in versionlocklist.stdout and not 'Keep installed : containerd.io-' + containerd_version in versionlocklist.stdout"

- name: install containerd.io package
  zypper:
    name: "{{ 'containerd.io=' + containerd_version }}"
    state: present
    update_cache: yes
  register: result
  until: result is success
  retries: 15
  delay: 60

- name: add versionlock for containerd
  command: zypper addlock containerd.io
  args:
    warn: false
  register: command_result
  changed_when: 'command_result.stdout is regex(".*lock has been successfully added.*")'

- name: remove versionlock for kubelet and kubectl packages
  command: zypper removelock {{ item }}
  with_items:
    - kubelet
    - kubectl
  args:
    warn: false
  ignore_errors: True
  register: command_result
  changed_when: 'command_result.stdout is regex(".*lock has been successfully removed.")'
  when:
    - versionlocklist is defined and versionlocklist.stdout is defined
    - item in versionlocklist.stdout
    - "not 'Keep installed : ' + item + '-' + package_versions.kubernetes_rpm in versionlocklist.stdout"

- name: install kubectl package
  zypper:
    name: "{{ 'kubectl-' + package_versions.kubernetes_rpm }}"
    state: present
    update_cache: yes
  register: result
  until: result is success
  retries: 15
  delay: 60

- name: install kubelet package
  zypper:
    name: "{{ 'kubelet-' + package_versions.kubernetes_rpm }}"
    state: present
    update_cache: yes
  register: kubelet_installation_rpm
  until: kubelet_installation_rpm is success
  retries: 15
  delay: 60
  notify:
    - reload systemd
    - restart kubelet

- name: add versionlock for kubelet and kubectl packages
  command: zypper addlock {{ item }}
  with_items:
    - kubelet
    - kubectl
  args:
    warn: false
  register: command_result
  changed_when: 'command_result.stdout is regex(".*lock has been successfully removed.")'

- name: install kubeadm package
  zypper:
    name: "{{ 'kubeadm-' + package_versions.kubernetes_rpm }}"
    state: present
    update_cache: yes
  register: result
  until: result is success
  retries: 15
  delay: 60
