---
- include: install-redhat.yaml
  when: ansible_os_family == "RedHat"

- include: install-suse.yaml
  when: ansible_os_family == "Suse"

- include: install-flatcar.yaml
  when: ansible_os_family == "Flatcar"

- include: install-debian.yaml
  when: ansible_os_family == "Debian"

- include: config.yaml
