---
- include_tasks: redhat.yaml
  when: ansible_os_family == "RedHat"

- include_tasks: suse.yaml
  when: ansible_os_family == "Suse"

- include_tasks: flatcar.yaml
  when: ansible_os_family == "Flatcar"

- include_tasks: debian.yaml
  when: ansible_os_family == "Debian"

- include_tasks: config.yaml
