---
# RPM
- name: add Konvoy Kubernetes rpm repository
  zypper_repository:
    name: kubernetes
    description: Konvoy Kubernetes package repository
    repo: "{{ kubernetes_rpm_suse_repository_url }}"
    disable_gpg_check: true
    autorefresh: true
  register: konvoy_repo_installation_rpm
  until: konvoy_repo_installation_rpm is success
  retries: 15
  delay: 60

- name: import Konvoy Kubernetes rpm repository key
  rpm_key:
    state: present
    key: "{{ kubernetes_rpm_suse_gpg_key_url }}"

- name: add Konvoy Containerd rpm repository
  zypper_repository:
    name: konvoy-packages
    description: Konvoy Containerd package repository
    repo: "{{ docker_rpm_suse_repository_url }}"
    disable_gpg_check: true
    autorefresh: true
  register: konvoy_repo_installation_rpm
  until: konvoy_repo_installation_rpm is success
  retries: 15
  delay: 60

- name: add Konvoy Containerd rpm repository key
  rpm_key:
    state: present
    key: "{{ docker_rpm_suse_gpg_key_url }}"
