---
- include_tasks: redhat.yaml
  when:
    - ansible_facts['os_family'] == "RedHat"
    - not offline_mode_enabled

- include_tasks: redhat-offline.yaml
  when:
    - ansible_facts['os_family'] == "RedHat"
    - offline_mode_enabled

- include_tasks: suse.yaml
  when: ansible_facts['os_family'] == "Suse"

- include_tasks: debian.yaml
  when:
    - ansible_facts['os_family'] == "Debian"
    - not offline_mode_enabled

- include_tasks: debian-offline.yaml
  when:
    - ansible_facts['os_family'] == "Debian"
    - offline_mode_enabled
