---
scenario:
  name: ec2_gpu
driver:
  name: ec2
platforms:
  - name: konvoyimage-centos7.9-${USER:-ci}-${HOSTNAME:-local}
    image_search_name: "CentOS 7.9.2009 x86_64"
    image_search_owner: "125523088429"
    region: us-east-1
    instance_type: p2.xlarge
    spot_price: false
    ssh_user: centos
  # test vault
  - name: konvoyimage-centos7.8-${USER:-ci}-${HOSTNAME:-local}
    image_search_name: "CentOS 7.8*"
    image_search_owner: "125523088429"
    region: us-east-1
    instance_type: p2.xlarge
    spot_price: false
    ssh_user: centos
  - name: konvoyimage-rhel7.9-${USER:-ci}-${HOSTNAME:-local}
    image_search_name: "RHEL-7.9_HVM-*"
    image_search_owner: "309956199498"
    region: us-east-1
    instance_type: p2.xlarge
    spot_price: false
    ssh_user: ec2-user
  - name: konvoyimage-flatcar-stable-${USER:-ci}-${HOSTNAME:-local}
    image_search_name: "Flatcar*stable*"
    image_search_owner: "075585003325"
    volume_name: /dev/xvda
    volume_size: 40
    region: us-east-1
    instance_type: p2.xlarge
    ssh_user: core
    spot_price: false
  - name: konvoyimage-ubuntu-22.04-${USER:-ci}-${HOSTNAME:-local}
    image_search_name: "*ubuntu-focal-22.04-amd64-server-*"
    image_search_owner: "099720109477"
    region: us-east-1
    instance_type: p2.xlarge
    ssh_user: ubuntu
    spot_price: false

provisioner:
  name: ansible
  log: true
  playbooks:
    ec2:
      create: ../ec2/create.yml
      destroy: ../ec2/destroy.yml
    converge: converge.yaml
  config_options:
    defaults:
      hash_behaviour: merge
  env:
    ANSIBLE_ROLES_PATH: "../../roles/"
  inventory:
    links:
      group_vars: ../../group_vars/
  lint:
    name: ansible-lint
    enabled: true
verifier:
  name: testinfra
