# Builds vSphere image template when a release tag is created
name: Upload VCD templates for Konvoy E2E tests
description: "Common workflow to upload template to VCD"

runs:
  using: "composite"
  steps:
    - name: upload VCD template
      shell: bash
      run: make infra.vcd.create

    - name: Run make destroy to clean up failed tests
      shell: bash
      if: ${{ always() }}
      run: make infra.vcd.destroy || true
