---
# automatically adds release labels to pull requests. The labels are decided based on configuration at "./.github/release.yaml"
name: Add release labels
on:
  pull_request_target:
    types:
      - opened
      - edited
jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: bcoe/conventional-release-labels@v1
