---
"on":
  pull_request_target:
    types:
      - opened
      - edited
name: conventional-release-labels
jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: bcoe/conventional-release-labels@v1
