---
name: Ansible Molecule Tests - Default

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main
      - release-*
    paths:
      - 'ansible/roles/gpu'
  pull_request:
    branches:
      - main
      - release-*
jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: Test
        run: make devkit.run
        env:
          WHAT: make molecule_test_gpu
