---
# Determines next release version
# release-please workflow analyzes commit messages in `main` branch since the last release
# and determines type of release: breaking, feature or bugfix.
# release-please will create a new PR or update an existing PR with release notes and next version bump.
# NOTE: This workflow does not create actual release. It determines next release version and create/updates PR for review.
on:
  push:
    branches:
      - main

name: Determine next release version
jobs:
  release-please:
    runs-on: 
    - self-hosted
    - small
    outputs:
      release_created: ${{ steps.release-please.outputs.release_created }}
      release_tag_name: ${{ steps.release-please.outputs.tag_name }}
      release_upload_url: ${{ steps.release-please.outputs.upload_url }}
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release-please
        with:
          token: ${{ secrets.MESOSPHERECI_USER_TOKEN }}
          release-type: go
          package-name: konvoy-image-builder
          changelog-types: >-
            [
              {"type":"feat","section":"Features","hidden":false},
              {"type":"fix","section":"Bug Fixes","hidden":false},
              {"type":"chore","section":"Miscellaneous","hidden":true}
            ]
