# Runs Azure tests when pull request opened, repopened or synchronized
name: Podman E2E Tests - Build AWS AMI
on:
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read
  id-token: write

jobs:
  rune2e:
    runs-on: ubuntu-22.04
    continue-on-error: false
    steps:
      - name: Checkout konvoy-image-builder repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
          cache: true

      - name: Login to dockerhub Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.NEXUS_USERNAME }}
          password: ${{ secrets.NEXUS_PASSWORD }}

      - name: Login to D2iQ's Mirror Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.D2IQ_DOCKER_MIRROR_REGISTRY}}
          username: ${{ secrets.NEXUS_USERNAME }}
          password: ${{ secrets.NEXUS_PASSWORD }}

      - name: Setup buildkit
        uses: docker/setup-buildx-action@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/konvoy-image-builder
          aws-region: us-west-2

      - name: Download GoReleaser
        run: go install github.com/goreleaser/goreleaser@v1.15.2

      - name: Build snapshot
        run:  |-
          make build-for-podman
          goreleaser build --config=.goreleaser-podman-e2e.yml --clean --skip-validate

      - name: Run E2E test for AWS centos 7.9 using podman
        run: |-
          KIB_CONTAINER_ENGINE=podman dist/konvoy-image-wrapper-for-podman_linux_amd64_v1/konvoy-image build aws images/ami/centos-79.yaml --dry-run
        env:
          GITHUB_TOKEN: ${{ secrets.MESOSPHERECI_USER_TOKEN }}
          KIB_CONTAINER_ENGINE: podman
