# Runs Azure tests when pull request opened, repopened or synchronized
name: Podman E2E Tests - Build GCP Image
on:
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read
  id-token: write

jobs:
  rune2e:
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
      - name: Checkout konvoy-image-builder repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
          cache: true

      - name: Login to dockerhub Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.NEXUS_USERNAME }}
          password: ${{ secrets.NEXUS_PASSWORD }}

      - name: Login to D2iQ's Mirror Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.D2IQ_DOCKER_MIRROR_REGISTRY}}
          username: ${{ secrets.NEXUS_USERNAME }}
          password: ${{ secrets.NEXUS_PASSWORD }}

      - name: Setup buildkit
        uses: docker/setup-buildx-action@v2
      
      - name: Download GoReleaser
        run: go install github.com/goreleaser/goreleaser@v1.15.2
      
      - name: Build snapshot
        run: make build.snapshot

      - name: Setup GOOGLE_APPLICATION_CREDENTIALS
        run: |-
          echo -n "${GOOGLE_APPLICATION_CREDENTIALS_E2E_BASE64}" | base64 --decode >> google-credentials.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=google-credentials.json" >> $GITHUB_ENV
        env:
          GOOGLE_APPLICATION_CREDENTIALS_E2E_BASE64: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_E2E_BASE64 }}

      - name: Run E2E test for GCP ubuntu 20.04 using podman
        run: |-
          dist/konvoy-image_linux_amd64_v1/konvoy-image build gcp images/gcp/ubuntu-2004.yaml --project-id=eng-ksphere-platform-e2e --network=kib-ssh-network
        env:
          GITHUB_TOKEN: ${{ secrets.MESOSPHERECI_USER_TOKEN }}
          KIB_CONTAINER_ENGINE: podman
