on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

permissions:
  contents: read
  id-token: write

name: Build Azure Images for Konvoy E2E tests
jobs:
  builde2e:
    strategy:
      fail-fast: false
      max-parallel: 10
      matrix:
        include:
          - os: "rocky 9.1"
            buildConfig: "basic"
          - os: "ubuntu 20.04"
            buildConfig: "basic"

    runs-on:
    - self-hosted
    - small
    continue-on-error: false
    steps:
      - name: Checkout konvoy-image-builder repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: true

      - name: Login to dockerhub Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.NEXUS_USERNAME }}
          password: ${{ secrets.NEXUS_PASSWORD }}

      - name: Login to D2iQ's Mirror Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.D2IQ_DOCKER_MIRROR_REGISTRY}}
          username: ${{ secrets.NEXUS_USERNAME }}
          password: ${{ secrets.NEXUS_PASSWORD }}

      - name: Setup buildkit
        uses: docker/setup-buildx-action@v3

      - name: Build Image ${{ matrix.os }} with ${{ matrix.buildConfig }} for Azure
        uses: magefile/mage-action@v3
        with:
          version: latest
          args: runE2e "${{ matrix.os }}" "${{ matrix.buildConfig }}" azure false
        env:
          GITHUB_TOKEN: ${{ secrets.MESOSPHERECI_USER_TOKEN }}
          AZURE_CLIENT_ID: "${{ secrets.AZURE_CLIENT_ID }}"
          AZURE_SUBSCRIPTION_ID: "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
          AZURE_TENANT_ID: "${{ secrets.AZURE_TENANT_ID }}"
          AZURE_CLIENT_SECRET: "${{ secrets.AZURE_CLIENT_SECRET }}"
