'on':
  pull_request:
    branches:
    - '*'

jobs:
  release-snap:
    name: release-snap
    runs-on: self-hosted

    steps:
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 'v1.18'
          check-latest: true

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download GoReleaser
        run: go install github.com/goreleaser/goreleaser@v1.11.5

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: mesosphereci
          password: ${{ secrets.DOCKER_PASS }}

      - name: setup buildkit
        uses: docker/setup-buildx-action@v2

      - name: Release
        run: make release-snapshot
        env:
          DOCKER_CLI_EXPERIMENTAL: "enabled"
          GITHUB_TOKEN: ${{ secrets.MESOSPHERECI_USER_TOKEN }}
          REPO_REV: ${{ github.ref_name }}
