# Builds GCP image when a release tag is created
name: Build GCP image for Konvoy E2E tests
on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

permissions:
  contents: read
  id-token: write

jobs:
  rune2e:
    strategy:
      fail-fast: false
      max-parallel: 10
      matrix:
        include:
          - os: "ubuntu 20.04"
            buildConfig: "basic"
    runs-on: 
    - self-hosted
    - small
    continue-on-error: false
    steps:
      - name: Checkout konvoy-image-builder repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
          cache: true

      - name: Login to dockerhub Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.NEXUS_USERNAME }}
          password: ${{ secrets.NEXUS_PASSWORD }}

      - name: Login to D2iQ's Mirror Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.D2IQ_DOCKER_MIRROR_REGISTRY}}
          username: ${{ secrets.NEXUS_USERNAME }}
          password: ${{ secrets.NEXUS_PASSWORD }}

      - name: Setup buildkit
        uses: docker/setup-buildx-action@v2

      - name: Setup GOOGLE_APPLICATION_CREDENTIALS
        run: |-
          echo -n "${GOOGLE_APPLICATION_CREDENTIALS_E2E_BASE64}" | base64 --decode >> google-credentials.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=google-credentials.json" >> $GITHUB_ENV
        env:
          GOOGLE_APPLICATION_CREDENTIALS_E2E_BASE64: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_E2E_BASE64 }}

      - name: Build GCP image for ${{ matrix.os }} with ${{ matrix.buildConfig }} configuration
        uses: magefile/mage-action@v2
        with:
          version: latest
          args: runE2e "${{ matrix.os }}" "${{ matrix.buildConfig }}" gcp false
        env:
          GITHUB_TOKEN: ${{ secrets.MESOSPHERECI_USER_TOKEN }}
