---
name: Test

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to dockerhub Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.NEXUS_USERNAME }}
          password: ${{ secrets.NEXUS_PASSWORD }}

      - name: Login to D2iQ's Mirror Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.D2IQ_DOCKER_MIRROR_REGISTRY}}
          username: ${{ secrets.NEXUS_USERNAME }}
          password: ${{ secrets.NEXUS_PASSWORD }}

      - name: Test
        run: make devkit.run
        env:
          WHAT: make test

      - uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8
        with:
          name: coverage
          path: coverage.xml
