---
name: Test Notrarizing

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - shalin/darwin-sig

jobs:

  notarize-release:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Snapshot
        run: make devkit.run
        env:
          WHAT: make build.snapshot

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: mesosphereci
          password: ${{ secrets.DOCKER_PASS }}

      - name: Import Code-Signing Certificates
        uses: Apple-Actions/import-codesign-certs@v1
        with:
          # The certificates in a PKCS12 file encoded as a base64 string
          p12-file-base64: ${{ secrets.APPLE_DEVELOPER_CERTIFICATE_P12_BASE64 }}
          # The password used to import the PKCS12 file.
          p12-password: ${{ secrets.APPLE_DEVELOPER_CERTIFICATE_PASSWORD }}

      - name: Install required binaries
        run: |
          brew tap mitchellh/gon
          brew install mitchellh/gon/gon

      - name: Release
        run: make devkit.run
        env:
          DOCKER_CLI_EXPERIMENTAL: "enabled"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AC_USERNAME: ${{ secrets.AC_USERNAME }}
          AC_PASSWORD: ${{ secrets.AC_PASSWORD }}
          WHAT: make release
      
      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: binaries
          path: |
            dist

