# Builds vSphere bastion host
name: Build vSphere bastion host for e2e tests
on:
  workflow_dispatch:
  push:
    branches:
      - 'shalin/*'

jobs:
  build-bastion:
    runs-on: 
    - self-hosted
    - small
    steps:
      - name: Checkout konvoy-image-builder repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install terraform
        uses: hashicorp/setup-terraform@v2

      - name: Setup SSH agent with private key to connect with pre-configured bastion host
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_BASTION_KEY_CONTENTS }}

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: create bastion host
        run: |
          git config --global url."https://git:${{ secrets.MESOSPHERECI_USER_TOKEN }}@github.com/mesosphere".insteadOf "https://github.com/mesosphere"
          git config --global url."https://${{ secrets.MESOSPHERECI_USER_TOKEN }}:x-oauth-basic@github.com/mesosphere".insteadOf ssh://git@github.com/mesosphere
          echo "${{ secrets.SSH_BASTION_PUBLIC_KEY_CONTENTS }}" > "${{github.workspace}}/hack/vsphere/bastion.pub"
          export TF_VAR_ssh_public_key="${{github.workspace}}/hack/vsphere/bastion.pub"
          cd hack/vsphere
          terraform init
          terraform apply --auto-approve
        shell: bash
        env:
          VSPHERE_USER: ${{ secrets.VSPHERE_USERNAME }}
          VSPHERE_PASSWORD: ${{ secrets.VSPHERE_PASSWORD }}
          VSPHERE_SERVER: ${{ secrets.VSPHERE_SERVER }}
          TF_VAR_datastore_name: ${{ secrets.VSPHERE_DATASTORE }}
